### ISSUE TITLE
Reconsider the default key bindings.

### ISSUE THREAD

**Issue by ADmad** [MehediDracula/PHP-Namespace-Resolver#1]
Please reconsider the default keybings this extension uses. For e.g. `F1` is already bound to "Show All Commands" by default and it's not good overriding such a commonly used binding.

IMHO it would be better to use a key combination by default for all the commands this extension provides.

**Comment by MehediDracula** [comment]
Hmm... I'm also thinking to change the default keybindings... can't think any good combination for those commands... any suggestions?

**Comment by ADmad** [comment]
Import: Ctrl + Alt + I
Expand: Ctrl + Alt + E
Sort: Ctrl + Alt + S

These would most likely not conflict with any existing shortcuts.

**Comment by MehediDracula** [comment]
Looks good to me... i'll update on next release. Thanks
