### ISSUE TITLE
Feature suggestion: Import missing namespaces

### ISSUE THREAD

**Issue by nerdo** [MehediDracula/PHP-Namespace-Resolver#12]
First of all, I love the plugin. It does everything I'm used to with a similar Sublime plugin, but there is one thing that I think could be extremely helpful.

Primary Use Case:
Refactoring.

Example:
Developer writes a function, or set of functions somewhere, and later realize it's time to refactor some of the functions into a new class for whatever reason (decoupling, etc.). Developer goes through the new class with the copied functions re-importing namespaces with PHP-Namespace-Resolver, but overlooks a namespace or two.

Suggestion:
Add a "Import Missing Namespaces" action which would essentially go through any class references in the file (e.g. new MyClass, MyClass::whatever) and run the Import Namespace command on each, prompting Developer to choose the correct namespace if it finds any class references that are ambiguous.

A similar "Expand Missing Namespaces" could be added as well, for completeness, though I think Import would be used more often.

**Comment by MehediDracula** [comment]
Hm... this would be a useful feature. I'll look into this to implement this feature

Thanks for your suggestion :blush:

**Comment by rrd108** [comment]
The feature should be added to the README
