### ISSUE TITLE
Feature: import and prepend before class name

### ISSUE THREAD

**Issue by filtration** [MehediDracula/PHP-Namespace-Resolver#13]
Sometimes we only have 1 reference to a class, and importing as a use statement can get large pretty quick

Can we have a shortcut to prepend the namespaces to the class, for example

**before the append** 

    public function index(User $user)
    {

    }

**after prepend**

    public function index(App\Models\User $user)
    {

    }

**Comment by MehediDracula** [comment]
Hit `ctrl+alt+e`
