### ISSUE TITLE
Feature suggestion: find unused imports

### ISSUE THREAD

**Issue by smbkr** [MehediDracula/PHP-Namespace-Resolver#15]
A feature I'd like to see and would find very useful would be the ability to scan a file for any imports that are unused, with options for either highlighting them (con: user has to manually remove them, pro: false positives caught by user) or optionally to auto-remove (con: potential for false positives).

**Comment by MehediDracula** [comment]
sorry for late reply.
why don't you use php cs fixer for that? this package is only for resolving namespaces

**Comment by pedzed** [comment]
I would like to have this feature as well.

> this package is only for resolving namespaces

Well, there is also sorting.

**Comment by jbrooksuk** [comment]
There is also https://styleci.io for a good CI integration.

**Comment by rrd108** [comment]
PHP Import Checker does this
https://marketplace.visualstudio.com/items?itemName=marabesi.php-import-checker

**Comment by MehediDracula** [comment]
@rrd108 Sure.
