### ISSUE TITLE
Disable Messages

### ISSUE THREAD

**Issue by evertramos** [MehediDracula/PHP-Namespace-Resolver#16]
Is it possible to disable the messages after using this plugin? 

![image](https://user-images.githubusercontent.com/905951/34382167-36a7a478-eaf4-11e7-9afe-ea01011a5b83.png)

Thanks!

**Comment by MehediDracula** [comment]
Add this to your settings

```json
"namespaceResolver.showMessageOnStatusBar": true
```

**Comment by evertramos** [comment]
Thanks! 

Sorry for my "newbiness"...
