### ISSUE TITLE
Extension is not working in v1.19.2

### ISSUE THREAD

**Issue by santigarcor** [MehediDracula/PHP-Namespace-Resolver#18]
First I want to thank you for this extension it's awesome, but recently it stopped working. When I run the import class or expand class  command nothing happens as you can see here:

![peek 2018-01-17 07-56](https://user-images.githubusercontent.com/7565417/35043885-3cf68bc8-fb5c-11e7-9684-68c136320f89.gif)

**Update:** I debugged the extension and the problem seems to be in this line: 

```js
let namespaces = await this.findNamespaces(resolving, files);
```
after stopping the execution there, the debug console shows `rejected promise not handled within 1 second`.

**Comment by MehediDracula** [comment]
I've just tested on vscode v1.19.2 it's working here
what is the version of the extension?

**Comment by santigarcor** [comment]
I have the 0.9.8. I think the problem happens when there are a lot of namespaces or files.

**Comment by MehediDracula** [comment]
can you please confirm this by testing on a small project?

**Comment by santigarcor** [comment]
I tested it in a smaller project and it worked fine

**Comment by MehediDracula** [comment]
i just tested on a large symfony app which has 150+ package. it's working here :confused:

**Comment by santigarcor** [comment]
It's weird, because for some reason in the debug console it shows this warning/error `rejected promise not handled within 1 second.`

**Comment by santigarcor** [comment]
The problem is that an exception is being thrown in this line inside the parseNamespaces method:
```js
if (textLine.startsWith('namespace ') || textLine.startsWith('<?php namespace ')) { // Here you allow the namespace in the same line as the php tag.
  let fqcn = `${textLine.match(/^namespace\s+(.+)?;/).pop()}\\${resolving}`; // But here the regex doesn't include that.
```
The problem is the regex, because when the namespace is not in a single line it doesn't match with the regex. I'll submit a PR to fix it.

**Comment by MehediDracula** [comment]
thanks for the PR :relieved:
