### ISSUE TITLE
Feature Suggestion: Generate Namespace For Current File

### ISSUE THREAD

**Issue by parttimenobody** [MehediDracula/PHP-Namespace-Resolver#22]
Hey,  not sure if this has been suggested before but it might be useful if we could get a command to add the namespace declaration to the current file.  

Say the working path were "App/Models/User.php" then the command would put "namespace App\Models;" at the top of the file.

I know PHPCompanion in Sublime supports that feature, granted I'm not sure how difficult that is to implement though.  I personally just find it pretty useful and I'm sure some others would as well.

Thanks much.

**Comment by MehediDracula** [comment]
thanks for the suggestion. I'll try to implement that
