### ISSUE TITLE
Replacing usestatements

### ISSUE THREAD

**Issue by crissi** [MehediDracula/PHP-Namespace-Resolver#23]
I often change a namespace of one of my files and therefore need to update the use statement in the file that uses it.

Right now this is not possible with this plugin, because the class already has a use statement and will ask for an alias.

I am thinking that if you do not enter anything in the "Enter an alias"-box, it will instead replace the use statement.

The box could say "Enter an alias or leave it empty to replace"

I would gladly make a pullrequest if you accept this feature.

**Comment by MehediDracula** [comment]
looks good to me. I'll accept the PR :)
