### ISSUE TITLE
Sorting doesn't work as expected

### ISSUE THREAD

**Issue by jonom** [MehediDracula/PHP-Namespace-Resolver#26]
Hello,

Found this extension today and it looks great, thanks! One thing I noticed is that sorting doesn't work the way I expect it to. Sorting is done only on the classname, it excludes the namespace. So I get this result:

```
use SilverStripe\Admin\ABCThing;
use SilverStripe\ORM\DataObject;
use SilverStripe\Admin\ModelAdmin;
```

but I expect this:

```
use SilverStripe\Admin\ABCThing;
use SilverStripe\Admin\ModelAdmin;
use SilverStripe\ORM\DataObject;
```

**Comment by MehediDracula** [comment]
By default, it will sort based on the namespace length. Add this setting  `"namespaceResolver.sortAlphabetically": true` to sort alphabetically.

**Comment by jonom** [comment]
Thanks, sorry I missed that in the settings documentation!
