### ISSUE TITLE
Version 1.0.5 stopped working with update to VSCode 1.23.0

### ISSUE THREAD

**Issue by matbeard** [MehediDracula/PHP-Namespace-Resolver#27]
Brilliant extension. I use it a lot. However, with the recent upgrade to VS Code, it's stopped working: no errors, just doesn't do anything.

Here's my VS Code environment:
Version 1.23.0
Commit 7c7da59c2333a1306c41e6e7b68d7f0caa7b3d45
Date 2018-05-03T16:44:55.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Any suggestions?

**Comment by MehediDracula** [comment]
Hm, that's weird I have the exact same version of VS Code installed on my machine and it's working perfectly here. can you please reinstall the extension?

**Comment by matbeard** [comment]
Strange. I've uninstalled VS Code, removed the extensions directory, re-installed VS Code and added the extension back again. Still no luck.

I'll try disabling other extensions to see if there's a conflict.

**Comment by MehediDracula** [comment]
Have you tried disabling other extensions? I've once found `PHP Intelephense` was causing an issue.

**Comment by Sell24** [comment]
I was having the same issue. Turns out that hiding the vendor folder using the files.exclude option in Preferences > Settings causes this not to work.

**Comment by MehediDracula** [comment]
Since this extension is using VS Code's API for searching files so your excluded files won't be searched by this extension.

**Comment by MehediDracula** [comment]
Closing this issue for now.
