### ISSUE TITLE
How to sort imports on save?

### ISSUE THREAD

**Issue by martinbean** [MehediDracula/PHP-Namespace-Resolver#28]
Hi, this package is great for sorting my imports using a keyboard shortcut. I’d like to sort imports on save as well.

I’ve tried adding this to my user settings:

```json
"[php]": {
    "editor.codeActionsOnSave": {
        "namespaceResolver.sort": true
    }
}
```

But imports don’t sort on save as expected. Do I need to do anything else to get the `namespaceResolver.sort` command to run when a **.php** file is saved?

**Comment by MehediDracula** [comment]
I'm not sure yet. I have to figure that out.

**Comment by MehediDracula** [comment]
I'm not sure yet why it's not working with the `editor.codeActionsOnSave`. But I have added a new config `namespaceResolver.sortOnSave` which will let you auto sort when you save a file.
