### ISSUE TITLE
Insert namespace

### ISSUE THREAD

**Issue by shouze** [MehediDracula/PHP-Namespace-Resolver#3]
Hi,

this extension looks very promising! 👏 

As almost every php project uses composer nowaday, and as psr-4 tends to be widely adopted too, should be cool to open composer.json to automatically implement the namespace of a newly created class, no?

I'm ok to help as I prefer by far this extension to bloated/complex extensions for php that we can found currently for VSCode.

**Comment by MehediDracula** [comment]
Hello, thanks for your idea. PRs are always welcome :)

**Comment by fetzi** [comment]
Maybe you are interested in my Extension, that implements this functionality 😉https://marketplace.visualstudio.com/items?itemName=fetzi.php-file-types

**Comment by MehediDracula** [comment]
@fetzi awesome... will give it a shot

**Comment by shouze** [comment]
@fetzi 🎉  such a nice extension! About the composer.json file lookup... as I'm used to code into some git monorepo (many php projects homed into the same git repository)... do you think it's possible to have a smarter composer.json resolver, that would try to find the nearest composer.json file relatively from the directory in the context we want to create a new class/interface/...?

**Comment by fetzi** [comment]
@shouze thanks a lot! Can you Open an issue in the project repository? Great ideal btw, will look into it immediately.

**Comment by MehediDracula** [comment]
closing this for now since this is not the purpose of this extension
