### ISSUE TITLE
Does not work with vendor classes on gitignore

### ISSUE THREAD

**Issue by andrecastelo** [MehediDracula/PHP-Namespace-Resolver#30]
Hey this is similar to #5.

On my end the hotkeys do not work with classes in the vendor folder, but works fine with classes in the current project. The issue, from what I found, is related to `.gitignore` - if I remove the vendor folder from it, then everything works fine. I tried replacing the intellisense plugin (tried PHP IntelliSense, IntelliSense-crane and Intelephense), without success.

Has this occurred in the past or is it resolvable with a specific configuration?

```
Version 1.24.0-insider
Commit 912fff91ac4ff1bff9695e8da69abd729f7ae956
Date 2018-05-18T05:11:07.195Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by MehediDracula** [comment]
Can you please try adding `"search.useIgnoreFiles": false` in your settings?

**Comment by andrecastelo** [comment]
Yeah, that didn't work. Since this is an insiders version, I tried with the stable one and everything works fine, with or without the `"search.useIgnoreFiles": false` in the settings.

This is the version that works fine:
```
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:01:43.521Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by andrecastelo** [comment]
This apparently has been fixed on the insiders version released today:
```
Version 1.24.0-insider
Commit 44ef3e9d1bd53c8992d883a5d9fd94e246402bae
Date 2018-05-28T05:10:38.478Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
