### ISSUE TITLE
Feature: Include external sources

### ISSUE THREAD

**Issue by manix** [MehediDracula/PHP-Namespace-Resolver#31]
This is pretty nice, the only reason I've ever stayed away from other editors than Netbeans is that they never had such good auto-import functionality. Neither does VSCode yet but it could get there with this plug in!

One feature that is key is to be able to auto-resolve *all* referenced classes instead of having to point to a class and then alt+ctrl+i however I see this is already mentioned in another feature request.

What would be really useful is also to be able to add paths of other sources, for example now my PHP project includes files from a directory that is not part of the project (a common repository), when trying to resolve a class from there I get an error that the class is not found. In Netbeans this problem is resolved by specifying paths of external sources and scanning them as well.

Thanks in advance, awesome work!

**Comment by manix** [comment]
Oh silly me, that's awesome, thanks!

After working a bit longer with the plugin I have some other recommendations but I'll just write them here to not spam with issues:

- When ctrl+click on a class name is useful to open the class file
- When a class is used with a FQCN and is then imported (alt+ctrl+i) it should be replaced with the class base name on all occurrences.
- When ctrl+click on a static or instance method call should take you to that method in the respective class.
- As of 5.6 functions and constants are also namespaced so would be useful to have import for them too.

**Comment by MehediDracula** [comment]
You can use [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client). It has all the features you've mentioned.
