### ISSUE TITLE
Exclude Multiple Folders

### ISSUE THREAD

**Issue by XanManZA** [MehediDracula/PHP-Namespace-Resolver#33]
Hi

Maybe I just don't understand glob matching that well but how do I exclude multiple folders?
Getting a VS Code settings error when I try the following
```
"namespaceResolver.exclude": [
        "**/node_modules/**",
        "**/vendor/{local package name}/vendor/**"
    ]
```

**Comment by ifaniqbal** [comment]
So, what is the correct config to do this?

**Comment by XanManZA** [comment]
Hi @ifaniqbal sorry this was years ago by now - I think I dropped this extension. The glob pattern above works correctly on intelephense extension. Good luck!
