### ISSUE TITLE
Automatic use statements?

### ISSUE THREAD

**Issue by mikebronner** [MehediDracula/PHP-Namespace-Resolver#4]
Hi, can this package create automatic use statements when adding classes from Intellisense? That is one of the features preventing me from moving from Atom to VS Code -- would love to find a way to have VSCode create use statements instead of resolving the class name inline.

Sorry if this is not what your package was designed to do, but I thought I would ask. :) Thanks!

**Comment by MehediDracula** [comment]
yes, it can automatically create use statements. just move the cursor over class and hit `ctrl+alt+i` or search for command `Import Class` on command palette. 

you can find all commands on [README](https://github.com/MehediDracula/PHP-Namespace-Resolver/blob/master/README.md)

btw, what did you mean by adding classes from Intellisense?

**Comment by mikebronner** [comment]
By automatic I mean without having to invoke the command manually, but I would like it to create the use statement when I select an item from the intellisense drop-down. Is it possible to configure your package in a way that does this?

**Comment by MehediDracula** [comment]
No, this package can't do this. 

I'm not sure if this is possible. I'll look into that.

**Comment by mikebronner** [comment]
Thanks! :) I think you will help out a lot of people who are looking at VSCode from Atom and SublimeText :).

**Comment by MehediDracula** [comment]
Did atom has this feature?

**Comment by mikebronner** [comment]
Yes, here is a gif: 
http://share.genealabs.com/4nO8yiV+

**Comment by MehediDracula** [comment]
That's cool. I'll look if I can implement this on VSCode.
