### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by bm-stschneider** [MehediDracula/PHP-Namespace-Resolver#44]
- Issue Type: `Bug`
- Extension Name: `php-namespace-resolver`
- Extension Version: `1.1.4`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.32.0-insider`

```json 
{
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 120,
		"activateCallTime": 6,
		"activateResolvedTime": 4,
		"activationEvent": "onLanguage:scss"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Language client is not ready yet"
		}
	]
}
```

**Comment by MehediDracula** [comment]
This issue does not seem to related to this extension.

**Comment by bm-stschneider** [comment]
this is what the reporter extension outputs

**Comment by MehediDracula** [comment]
The activation event is on SCSS. But this extension has activation event only in PHP language.
