### ISSUE TITLE
Import Namespace Missing?

### ISSUE THREAD

**Issue by aronquiray** [MehediDracula/PHP-Namespace-Resolver#49]
on the image "Demo" it has like Import namespace. where as on the latest version, it doesn't have.. 
![screenshot_992](https://user-images.githubusercontent.com/13714092/53702211-574c7100-3e3f-11e9-8105-be2dd713308f.png)

**Comment by MehediDracula** [comment]
What version are you running? As i see it's there.

![image](https://user-images.githubusercontent.com/10138936/53833997-1cb81500-3fb4-11e9-80b0-0464a9a00d0d.png)

**Comment by aronquiray** [comment]
the latest one. just downloaded it

**Comment by aronquiray** [comment]
![screenshot_997](https://user-images.githubusercontent.com/13714092/53841113-ee97fc80-3fd6-11e9-93d1-ad592fe3049b.png)
this one is not present as you can see on my previous screenshot. Is this a bug for me only?

**Comment by MehediDracula** [comment]
"Import Namespace" is renamed to "Import Class"

**Comment by aronquiray** [comment]
I noticed that. but there are some which cant be import directly right?
like on the deep namespaces
