### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by mikebronner** [MehediDracula/PHP-Namespace-Resolver#5]
When trying to import a class to create the use statement, I get the following error: Class App\User not found. I'm probably doing something wrong on my end. Any thoughts? Thanks!

**Comment by mikebronner** [comment]
I switched intellisense providers, and it seemed to work.

**Comment by MehediDracula** [comment]
if you're using [PHP IntelliSense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) try uninstalling and reinstalling PHP IntelliSense.

**Comment by mikebronner** [comment]
yea, I switched to intellisense-crane
