### ISSUE TITLE
Feature suggestions: trim and auto-determine

### ISSUE THREAD

**Issue by mikebronner** [MehediDracula/PHP-Namespace-Resolver#6]
I would like to recommend two improvements that might streamline the use of the plugin:

1. Automatically trim the namespace from the class name when importing, if it exists. For example
  ```php
  $test = new \App\User;
  //should become, after import:
  $test = new User;
  ```
2. If the class already has the namespace preceding it, automatically capture that and use it to resolve which class to import, instead of providing the drop-down window to the user.

Thanks for listening, keep up the good work!
~Mike

**Comment by MehediDracula** [comment]
Looks good to me. I'll work in this when i'm free

**Comment by mikebronner** [comment]
I would help, but I have never created a VSCode plugin before. :) can you point to any good starter tutorials to get myself familiar?

**Comment by MehediDracula** [comment]
Start from [here](https://code.visualstudio.com/docs/extensions/overview). Also, see the [APIs](https://code.visualstudio.com/docs/extensionAPI/vscode-api) provided by VSCode.

**Comment by mikebronner** [comment]
Thx! Also, the suggestions above have been implemented by PHP Inteliphense, it might give you some ideas on an approach to take. I will look at the links you provided. :)

**Comment by MehediDracula** [comment]
i have tried php Inteliphense. but last time when i tried `Add Use Declaration` command it did not work. so i had to create this package.

**Comment by MehediDracula** [comment]
Added this feature. 

but for now, it doesn't scan files to determine the existence of the class. if a fqcn is found it just import that and trim the class
