### ISSUE TITLE
Import notifications suggestion

### ISSUE THREAD

**Issue by gayanhewa** [MehediDracula/PHP-Namespace-Resolver#7]
Import notifications seems to be a bit distracting : 
https://github.com/MehediDracula/PHP-Namespace-Resolver/blob/cf676f93f94f725407644d3ebd1e1f270c7d6f9c/src/extension.js#L124

Failure notifications are alright, but success notifications require a force close. I think its ideal to move it to the status bar at the bottom. Less distracting.

**Comment by MehediDracula** [comment]
This is already possible. you can configure to show messages on the status bar.

Add this snippet to your settings file.

```json
{
    "namespaceResolver.showMessageOnStatusBar": true
}
```

**Comment by gayanhewa** [comment]
👍
