### ISSUE TITLE
Does not work with vendor classes

### ISSUE THREAD

**Issue by binarious** [MehediDracula/PHP-Namespace-Resolver#8]
I tried this package in my Symfony application and it does work for classes inside my app, but I can't import things from the vendor folder (e.g. Doctrine, Symfony, etc):

> Class 'Request' not found.

Maybe similar to https://github.com/MehediDracula/PHP-Namespace-Resolver/issues/5. I'm using PHP IntelliSense and already tried reinstalling it as mentioned in the other issue.

**Comment by MehediDracula** [comment]
Can you fully uninstall PHP IntelliSense and give it a shot?

**Comment by binarious** [comment]
Tried aswell. It didn't work.

**Comment by binarious** [comment]
Is there a way to debug what goes wrong?

**Comment by MehediDracula** [comment]
i just tested on a symfony application it's working here :confused: can plz try on a fresh symfony installation?

![screenshot](https://user-images.githubusercontent.com/10138936/31005800-13b88ae0-a51c-11e7-9740-c04e7e90da93.png)

**Comment by binarious** [comment]
I found the problem. It doesn't work when you have added `**/vendor` to the `files.exclude` settings. Is this intended? I don't want to see the results from `vendor` in my Quick Open Panel, but I'd like PHP-Namespace-Resolver to also look in `vendor`.

**Comment by binarious** [comment]
`search.exclude` does the trick. Thank you for your time.
